# This parent pipeline only runs and routes to the correct child workflow after validation checks.

name: Parent Pipeline

on:
  push:
    branches:
      - '*' # Matches any branch
  pull_request:
    branches:
      - '*' # Matches pull requests to any branch

jobs:
  determine-workflow:
    name: Determine Workflow Context
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.determine.outputs.branch }}
      event_name: ${{ steps.determine.outputs.event }}
    steps:
      - id: determine
        name: Extract Branch and Event
        run: |
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "event=${{ github.event_name }}" >> $GITHUB_OUTPUT

  trigger-validation:
    name: Trigger Validation Workflow
    needs: determine-workflow
    uses: ./.github/workflows/validation-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch }}
      event_name: ${{ needs.determine-workflow.outputs.event }}

  trigger-contributor-workflow:
    name: Trigger Contributor Workflow
    needs: trigger-validation
    if: |
      github.event_name == 'push' &&
      needs.determine-workflow.outputs.branch != 'main' &&
      needs.determine-workflow.outputs.branch != 'qa' &&
      needs.determine-workflow.outputs.branch != 'beta'
    uses: ./.github/workflows/contributor-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch }}
      event_name: ${{ needs.determine-workflow.outputs.event }}

  trigger-qa-workflow:
    name: Trigger QA Workflow
    needs: trigger-validation
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'qa'
    uses: ./.github/workflows/qa-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch }}
      event_name: ${{ needs.determine-workflow.outputs.event }}

  trigger-beta-workflow:
    name: Trigger Beta Workflow
    needs: trigger-validation
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'beta'
    uses: ./.github/workflows/beta-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch }}
      event_name: ${{ needs.determine-workflow.outputs.event }}

  trigger-main-workflow:
    name: Trigger Main Workflow
    needs: trigger-validation
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'main'
    uses: ./.github/workflows/main-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch }}
      event_name: ${{ needs.determine-workflow.outputs.event }}
