name: Parent Pipeline

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
        type: string
      event_name:
        description: 'Event name'
        required: true
        type: string
      workflow:
        description: 'Workflow to trigger'
        required: true
        type: string

jobs:
  trigger-workflow:
    name: Trigger Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Workflow
        if: ${{ inputs.workflow == 'main' }}
        uses: ./.github/workflows/main-workflow.yml
        with:
          branch_name: ${{ inputs.branch_name }}
          event_name: ${{ inputs.event_name }}

      - name: Trigger QA Workflow
        if: ${{ inputs.workflow == 'qa' }}
        uses: ./.github/workflows/qa-workflow.yml
        with:
          branch_name: ${{ inputs.branch_name }}
          event_name: ${{ inputs.event_name }}

      - name: Trigger Validation Workflow
        if: ${{ inputs.workflow == 'validation' }}
        uses: ./.github/workflows/validation-workflow.yml
        with:
          branch_name: ${{ inputs.branch_name }}
          event_name: ${{ inputs.event_name }}

      - name: Trigger Beta Workflow
        if: ${{ inputs.workflow == 'beta' }}
        uses: ./.github/workflows/beta-workflow.yml
        with:
          branch_name: ${{ inputs.branch_name }}
          event_name: ${{ inputs.event_name }}

      - name: Trigger Contributor Workflow
        if: ${{ inputs.workflow == 'contributor' }}
        uses: ./.github/workflows/contributor-workflow.yml
        with:
          branch_name: ${{ inputs.branch_name }}
          event_name: ${{ inputs.event_name }}
