# This parent pipeline only runs and routes to the correct child workflow after validation checks.

# Parent pipeline to validate and trigger child workflows

name: Parent Pipeline

on:
  push:
    branches:
      - '*'  # Matches any branch
  pull_request:
    branches:
      - '*'  # Matches pull requests to any branch

jobs:
  determine-workflow:
    name: Determine Workflow Context
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.determine.outputs.branch }}
      event_name: ${{ steps.determine.outputs.event }}
    steps:
      - name: Extract Branch and Event
        id: determine
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          echo "::set-output name=branch::${{ github.ref_name }}"
          echo "::set-output name=event::${{ github.event_name }}"

  trigger-validation:
    name: Trigger Validation Workflow
    needs: determine-workflow
    uses: ./.github/workflows/validation-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}

  trigger-contributor-workflow:
    name: Trigger Contributor Workflow
    needs: [trigger-validation]
    uses: ./.github/workflows/contributor-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'push' &&
      needs.determine-workflow.outputs.branch_name != 'main' &&
      needs.determine-workflow.outputs.branch_name != 'qa' &&
      needs.determine-workflow.outputs.branch_name != 'beta'

  trigger-qa-workflow:
    name: Trigger QA Workflow
    needs: [trigger-validation]
    uses: ./.github/workflows/qa-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'qa'

  trigger-beta-workflow:
    name: Trigger Beta Workflow
    needs: [trigger-validation]
    uses: ./.github/workflows/beta-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'beta'

  trigger-main-workflow:
    name: Trigger Main Workflow
    needs: [trigger-validation]
    uses: ./.github/workflows/main-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'main'
