# This parent pipeline only runs and routes to the correct child workflow after validation checks.

name: Parent Pipeline

on:
  push:
    branches:
      - '*' # Matches any branch
  pull_request:
    branches:
      - '*' # Matches pull requests to any branch

jobs:
  determine-workflow:
    name: Determine Branch and Event
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.determine.outputs.branch_name }}
      base_branch: ${{ steps.determine.outputs.base_branch }}
      event_name: ${{ steps.determine.outputs.event_name }}
    steps:
      - name: Extract Information
        id: determine
        run: |
          echo "Branch Name: ${{ github.ref_name }}"
          echo "Base Branch: ${{ github.base_ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "::set-output name=branch_name::${{ github.ref_name }}"
          echo "::set-output name=base_branch::${{ github.base_ref }}"
          echo "::set-output name=event_name::${{ github.event_name }}"

  trigger-contributor-workflow:
    needs: determine-workflow
    name: Contributor Workflow
    uses: ./.github/workflows/contributor-workflow.yml
    env:
      BRANCH_NAME: ${{ needs.determine-workflow.outputs.branch_name }}
      EVENT_NAME: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'push' &&
      needs.determine-workflow.outputs.branch_name != 'main' &&
      needs.determine-workflow.outputs.branch_name != 'qa' &&
      needs.determine-workflow.outputs.branch_name != 'beta'

  trigger-qa-workflow:
    needs: determine-workflow
    name: QA Workflow
    uses: ./.github/workflows/qa-workflow.yml
    env:
      BRANCH_NAME: ${{ needs.determine-workflow.outputs.branch_name }}
      EVENT_NAME: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'qa'

  trigger-beta-workflow:
    needs: determine-workflow
    name: Beta Workflow
    uses: ./.github/workflows/beta-workflow.yml
    env:
      BRANCH_NAME: ${{ needs.determine-workflow.outputs.branch_name }}
      EVENT_NAME: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'beta'

  trigger-main-workflow:
    needs: determine-workflow
    name: Main Workflow
    uses: ./.github/workflows/main-workflow.yml
    env:
      BRANCH_NAME: ${{ needs.determine-workflow.outputs.branch_name }}
      EVENT_NAME: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'main'
