# This parent pipeline only runs and routes to the correct child workflow after validation checks.

# This parent pipeline only runs and routes to the correct child workflow after validation checks.

name: Parent Pipeline

on:
  push:
    branches:
      - '*' # Matches any branch
  pull_request:
    branches:
      - '*' # Matches pull requests to any branch

jobs:
  trigger-validation:
    name: Trigger Validation Workflow
    uses: ./.github/workflows/validation-workflow.yml
    with:
      branch_name: ${{ github.ref_name }}
      event_name: ${{ github.event_name }}

  determine-workflow:
    needs: trigger-validation
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.determine.outputs.branch }}
      base_branch: ${{ steps.determine.outputs.base_branch }}
      event_name: ${{ steps.determine.outputs.event }}
    steps:
      - name: Determine Branch and Event
        id: determine
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Base Branch: ${{ github.base_ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "::set-output name=branch::${{ github.ref_name }}"
          echo "::set-output name=base_branch::${{ github.base_ref }}"
          echo "::set-output name=event::${{ github.event_name }}"

  trigger-contributor-workflow:
    needs: [determine-workflow]
    name: Trigger Contributor Workflow
    uses: ./.github/workflows/contributor-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'push' &&
      needs.determine-workflow.outputs.branch_name != 'main' &&
      needs.determine-workflow.outputs.branch_name != 'qa' &&
      needs.determine-workflow.outputs.branch_name != 'beta'

  trigger-qa-workflow:
    needs: [determine-workflow]
    name: Trigger QA Workflow
    uses: ./.github/workflows/qa-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'qa'

  trigger-beta-workflow:
    needs: [determine-workflow]
    name: Trigger Beta Workflow
    uses: ./.github/workflows/beta-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'beta'

  trigger-main-workflow:
    needs: [determine-workflow]
    name: Trigger Main Workflow
    uses: ./.github/workflows/main-workflow.yml
    with:
      branch_name: ${{ needs.determine-workflow.outputs.branch_name }}
      event_name: ${{ needs.determine-workflow.outputs.event_name }}
    if: |
      github.event_name == 'pull_request' &&
      needs.determine-workflow.outputs.base_branch == 'main'
